use super::{parser::*, CcError, Span};
use std::collections::{HashMap, HashSet};

#[derive(Clone)]
struct Sig {
    ret: Type,
    params: Vec<Type>,
    defined: bool,
}
#[derive(Clone, Copy)]
enum Loc {
    Local(usize, Type),
    Param(usize, Type),
    Global(Type),
}

pub fn generate(program: &Program) -> Result<String, Vec<CcError>> {
    let mut c = Compiler {
        globals: HashMap::new(),
        funcs: HashMap::new(),
        errors: vec![],
        label: 0,
        used_runtime: false,
    };
    c.collect(program);
    if !c.errors.is_empty() {
        return Err(c.errors);
    }
    let Some(main) = c.funcs.get("main") else {
        return Err(vec![CcError::new(
            Span { line: 1, column: 1 },
            "missing required `int main(void)` definition",
        )]);
    };
    if main.ret != Type::Int || !main.params.is_empty() || !main.defined {
        return Err(vec![CcError::new(
            Span { line: 1, column: 1 },
            "entry point must be defined as `int main(void)`",
        )]);
    }
    let mut out = String::from("; generated by ex3 cc\nORG 0x0010\nCALL main\nHLT\n");
    for item in &program.items {
        if let Item::Function(f) = item {
            if f.body.is_some() {
                match c.function(f) {
                    Ok(s) => out.push_str(&s),
                    Err(e) => c.errors.push(e),
                }
            }
        }
    }
    if c.used_runtime {
        out.push_str(RUNTIME);
    }
    for item in &program.items {
        if let Item::Global(g) = item {
            let value = match &g.init {
                Some(e) => match const_expr(e) {
                    Ok((v, _)) => v,
                    Err(m) => {
                        c.errors.push(CcError::new(e.span, m));
                        0
                    }
                },
                None => 0,
            };
            out.push_str(&format!("{}: HEX {value:08x}\n", g.name));
        }
    }
    out.push_str("END\n");
    if c.errors.is_empty() {
        Ok(out)
    } else {
        Err(c.errors)
    }
}

struct Compiler {
    globals: HashMap<String, Type>,
    funcs: HashMap<String, Sig>,
    errors: Vec<CcError>,
    label: usize,
    used_runtime: bool,
}
impl Compiler {
    fn collect(&mut self, p: &Program) {
        self.funcs.insert(
            "putchar".into(),
            Sig {
                ret: Type::Void,
                params: vec![Type::Int],
                defined: true,
            },
        );
        self.funcs.insert(
            "getchar".into(),
            Sig {
                ret: Type::Int,
                params: vec![],
                defined: true,
            },
        );
        for i in &p.items {
            match i {
                Item::Global(g) => {
                    if reserved(&g.name)
                        || self.globals.contains_key(&g.name)
                        || self.funcs.contains_key(&g.name)
                    {
                        self.errors.push(CcError::new(
                            g.span,
                            format!("duplicate or reserved global `{}`", g.name),
                        ));
                    } else {
                        self.globals.insert(g.name.clone(), g.ty);
                    }
                }
                Item::Function(f) => {
                    if f.name == "putchar" || f.name == "getchar" {
                        let expected = self.funcs.get(&f.name).unwrap();
                        let params: Vec<_> = f.params.iter().map(|p| p.ty).collect();
                        if f.body.is_some() || f.ret != expected.ret || params != expected.params {
                            self.errors.push(CcError::new(
                                f.span,
                                format!("invalid redeclaration of reserved function `{}`", f.name),
                            ));
                        }
                        continue;
                    }
                    if reserved(&f.name) || self.globals.contains_key(&f.name) {
                        self.errors.push(CcError::new(
                            f.span,
                            format!("duplicate or reserved function `{}`", f.name),
                        ));
                        continue;
                    }
                    let sig = Sig {
                        ret: f.ret,
                        params: f.params.iter().map(|p| p.ty).collect(),
                        defined: f.body.is_some(),
                    };
                    if let Some(old) = self.funcs.get_mut(&f.name) {
                        if old.ret != sig.ret
                            || old.params != sig.params
                            || old.defined && sig.defined
                        {
                            self.errors.push(CcError::new(
                                f.span,
                                format!("conflicting or duplicate declaration of `{}`", f.name),
                            ))
                        } else {
                            old.defined |= sig.defined
                        }
                    } else {
                        self.funcs.insert(f.name.clone(), sig);
                    }
                }
            }
        }
    }
    fn fresh(&mut self, p: &str) -> String {
        let n = self.label;
        self.label += 1;
        format!("__cc_{p}_{n}")
    }
    fn function(&mut self, f: &Function) -> Result<String, CcError> {
        let body = f.body.as_ref().unwrap();
        if f.ret != Type::Void && !definitely_returns(body) {
            return Err(CcError::new(
                f.span,
                format!(
                    "non-void function `{}` may reach the end without returning a value",
                    f.name
                ),
            ));
        }
        let locals = count_locals(body);
        let temps = max_temps_stmt(body).max(2);
        let frame = locals + temps;
        if frame > 32767 || frame + f.params.len() + 1 > 32767 {
            return Err(CcError::new(f.span, "function stack frame is too large"));
        }
        let end = self.fresh("return");
        let labels = collect_labels(body, &f.name)?;
        let mut g = FnGen {
            c: self,
            out: format!("{}:\nADJSP -{frame}\n", f.name),
            frame,
            locals,
            next_local: 0,
            scopes: vec![HashMap::new()],
            params: HashMap::new(),
            ret: f.ret,
            end,
            breaks: vec![],
            continues: vec![],
            user_labels: labels,
        };
        let mut seen = HashSet::new();
        for (i, p) in f.params.iter().enumerate() {
            if !seen.insert(p.name.clone()) {
                return Err(CcError::new(
                    p.span,
                    format!("duplicate parameter `{}`", p.name),
                ));
            }
            g.params.insert(p.name.clone(), (i, p.ty));
        }
        g.stmt(body, 0)?;
        g.out.push_str(&format!("{}:\nADJSP {frame}\nRET\n", g.end));
        Ok(g.out)
    }
}

struct FnGen<'a> {
    c: &'a mut Compiler,
    out: String,
    frame: usize,
    locals: usize,
    next_local: usize,
    scopes: Vec<HashMap<String, (usize, Type)>>,
    params: HashMap<String, (usize, Type)>,
    ret: Type,
    end: String,
    breaks: Vec<String>,
    continues: Vec<String>,
    user_labels: HashMap<String, String>,
}
impl FnGen<'_> {
    fn emit(&mut self, s: impl AsRef<str>) {
        self.out.push_str(s.as_ref());
        self.out.push('\n')
    }
    fn loc(&self, n: &str) -> Option<Loc> {
        for s in self.scopes.iter().rev() {
            if let Some(&(i, t)) = s.get(n) {
                return Some(Loc::Local(i, t));
            }
        }
        if let Some(&(i, t)) = self.params.get(n) {
            return Some(Loc::Param(i, t));
        }
        self.c.globals.get(n).copied().map(Loc::Global)
    }
    fn offset(&self, l: Loc, shift: usize) -> Option<(usize, Type)> {
        match l {
            Loc::Local(i, t) => Some((i + shift, t)),
            Loc::Param(i, t) => Some((self.frame + 1 + i + shift, t)),
            Loc::Global(_) => None,
        }
    }
    fn load_loc(&mut self, l: Loc, shift: usize) {
        if let Some((o, _)) = self.offset(l, shift) {
            self.emit(format!("LDSP {o}"))
        } else if let Loc::Global(_) = l {
            unreachable!()
        }
    }
    fn load_name(&mut self, n: &str, span: Span, shift: usize) -> Result<Type, CcError> {
        let l = self
            .loc(n)
            .ok_or_else(|| CcError::new(span, format!("undeclared identifier `{n}`")))?;
        match l {
            Loc::Global(t) => {
                self.emit(format!("LDA {n}"));
                Ok(t)
            }
            _ => {
                let t = self.offset(l, shift).unwrap().1;
                self.load_loc(l, shift);
                Ok(t)
            }
        }
    }
    fn store_name(&mut self, n: &str, span: Span, shift: usize) -> Result<Type, CcError> {
        let l = self
            .loc(n)
            .ok_or_else(|| CcError::new(span, format!("undeclared identifier `{n}`")))?;
        match l {
            Loc::Global(t) => {
                self.emit(format!("STA {n}"));
                Ok(t)
            }
            _ => {
                let (o, t) = self.offset(l, shift).unwrap();
                self.emit(format!("STSP {o}"));
                Ok(t)
            }
        }
    }
    fn temp(&self, d: usize, shift: usize) -> usize {
        self.locals + d + shift
    }
    fn stmt(&mut self, s: &Stmt, shift: usize) -> Result<(), CcError> {
        match &s.kind {
            StmtKind::Empty => {}
            StmtKind::Expr(e) => {
                self.expr(e, 0, shift)?;
            }
            StmtKind::Block(xs) => {
                self.scopes.push(HashMap::new());
                for x in xs {
                    self.stmt(x, shift)?
                }
                self.scopes.pop();
            }
            StmtKind::Decl(n, t, init) => {
                if self.scopes.last().unwrap().contains_key(n)
                    || (self.scopes.len() == 2 && self.params.contains_key(n))
                {
                    return Err(CcError::new(s.span, format!("redeclaration of `{n}`")));
                }
                let slot = self.next_local;
                self.next_local += 1;
                if let Some(e) = init {
                    let et = self.expr(e, 0, shift)?;
                    scalar(et, e.span)?;
                    self.emit(format!("STSP {}", slot + shift));
                }
                self.scopes
                    .last_mut()
                    .unwrap()
                    .insert(n.clone(), (slot, *t));
            }
            StmtKind::If(c, a, b) => {
                scalar(self.expr(c, 0, shift)?, c.span)?;
                self.emit("CMP 0");
                let els = self.c.fresh("else");
                let end = self.c.fresh("ifend");
                self.emit(format!("BEQ {els}"));
                self.stmt(a, shift)?;
                self.emit(format!("JMP {end}"));
                self.emit(format!("{els}:"));
                if let Some(b) = b {
                    self.stmt(b, shift)?
                }
                self.emit(format!("{end}:"));
            }
            StmtKind::While(c, b) => {
                let top = self.c.fresh("while");
                let end = self.c.fresh("wend");
                self.emit(format!("{top}:"));
                scalar(self.expr(c, 0, shift)?, c.span)?;
                self.emit("CMP 0");
                self.emit(format!("BEQ {end}"));
                self.breaks.push(end.clone());
                self.continues.push(top.clone());
                self.stmt(b, shift)?;
                self.continues.pop();
                self.breaks.pop();
                self.emit(format!("JMP {top}"));
                self.emit(format!("{end}:"));
            }
            StmtKind::Break => {
                let x = self
                    .breaks
                    .last()
                    .ok_or_else(|| CcError::new(s.span, "`break` is not inside while or switch"))?;
                self.emit(format!("JMP {x}"));
            }
            StmtKind::Continue => {
                let x = self
                    .continues
                    .last()
                    .ok_or_else(|| CcError::new(s.span, "`continue` is not inside while"))?;
                self.emit(format!("JMP {x}"));
            }
            StmtKind::Goto(n) => {
                let x = self
                    .user_labels
                    .get(n)
                    .ok_or_else(|| CcError::new(s.span, format!("undefined label `{n}`")))?;
                self.emit(format!("JMP {x}"));
            }
            StmtKind::Label(n, b) => {
                let x = self.user_labels[n].clone();
                self.emit(format!("{x}:"));
                self.stmt(b, shift)?;
            }
            StmtKind::Return(e) => {
                match (self.ret, e) {
                    (Type::Void, None) => {}
                    (Type::Void, Some(_)) => {
                        return Err(CcError::new(s.span, "void function cannot return a value"))
                    }
                    (_, None) => {
                        return Err(CcError::new(
                            s.span,
                            "non-void function must return a value",
                        ))
                    }
                    (_, Some(e)) => {
                        scalar(self.expr(e, 0, shift)?, e.span)?;
                    }
                }
                self.emit(format!("JMP {}", self.end));
            }
            StmtKind::Switch(e, parts) => self.switch_stmt(e, parts, s.span, shift)?,
        }
        Ok(())
    }
    fn switch_stmt(
        &mut self,
        e: &Expr,
        parts: &[SwitchPart],
        span: Span,
        shift: usize,
    ) -> Result<(), CcError> {
        let ty = self.expr(e, 0, shift)?;
        scalar(ty, e.span)?;
        let slot = self.temp(0, shift);
        self.emit(format!("STSP {slot}"));
        let end = self.c.fresh("swend");
        let mut labels = vec![];
        let mut cases = HashSet::new();
        let mut default = None;
        for p in parts {
            match p {
                SwitchPart::Case(x, s) => {
                    let (v, _) = const_expr(x).map_err(|m| CcError::new(*s, m))?;
                    if !cases.insert(v) {
                        return Err(CcError::new(*s, "duplicate case value"));
                    }
                    labels.push(Some(self.c.fresh("case")));
                }
                SwitchPart::Default(s) => {
                    if default.is_some() {
                        return Err(CcError::new(*s, "duplicate default label"));
                    }
                    let l = self.c.fresh("default");
                    default = Some(l.clone());
                    labels.push(Some(l));
                }
                SwitchPart::Stmt(_) => labels.push(None),
            }
        }
        for (p, l) in parts.iter().zip(&labels) {
            if let SwitchPart::Case(x, _) = p {
                let (v, _) = const_expr(x).unwrap();
                self.load_const(v);
                self.emit(format!("CMPSP {slot}"));
                self.emit(format!("BEQ {}", l.as_ref().unwrap()));
            }
        }
        self.emit(format!("JMP {}", default.as_ref().unwrap_or(&end)));
        self.breaks.push(end.clone());
        self.scopes.push(HashMap::new());
        for (p, l) in parts.iter().zip(labels) {
            if let Some(l) = l {
                self.emit(format!("{l}:"))
            }
            if let SwitchPart::Stmt(s) = p {
                self.stmt(s, shift)?
            }
        }
        self.scopes.pop();
        self.breaks.pop();
        self.emit(format!("{end}:"));
        let _ = span;
        Ok(())
    }
    fn expr(&mut self, e: &Expr, d: usize, shift: usize) -> Result<Type, CcError> {
        match &e.kind {
            ExprKind::Number(v, u) => {
                self.load_const(*v);
                Ok(if *u { Type::UInt } else { Type::Int })
            }
            ExprKind::Var(n) => self.load_name(n, e.span, shift),
            ExprKind::Assign(n, x) => {
                let t = self.expr(x, d, shift)?;
                scalar(t, x.span)?;
                self.store_name(n, e.span, shift)
            }
            ExprKind::Unary(op, x) => {
                let t = self.expr(x, d, shift)?;
                scalar(t, x.span)?;
                match op {
                    UnOp::Plus => {}
                    UnOp::BitNot => self.emit("CMA"),
                    UnOp::Neg => {
                        let s = self.temp(d, shift);
                        self.emit(format!("STSP {s}"));
                        self.emit("CLA");
                        self.emit(format!("SUBSP {s}"));
                    }
                    UnOp::Not => {
                        let yes = self.c.fresh("not");
                        let end = self.c.fresh("notend");
                        self.emit("CMP 0");
                        self.emit(format!("BEQ {yes}"));
                        self.emit("LDA 0");
                        self.emit(format!("JMP {end}"));
                        self.emit(format!("{yes}:"));
                        self.emit("LDA 1");
                        self.emit(format!("{end}:"));
                    }
                }
                Ok(if *op == UnOp::Not { Type::Int } else { t })
            }
            ExprKind::Binary(op, a, b) if matches!(op, BinOp::And | BinOp::Or) => {
                self.logical(*op, a, b, d, shift)
            }
            ExprKind::Binary(op, a, b) => {
                let at = self.expr(a, d, shift)?;
                scalar(at, a.span)?;
                let l = self.temp(d, shift);
                self.emit(format!("STSP {l}"));
                let bt = self.expr(b, d + 1, shift)?;
                scalar(bt, b.span)?;
                let r = self.temp(d + 1, shift);
                self.emit(format!("STSP {r}"));
                let common = if at == Type::UInt || bt == Type::UInt {
                    Type::UInt
                } else {
                    Type::Int
                };
                match op {
                    BinOp::Add | BinOp::Sub | BinOp::BitAnd | BinOp::BitXor | BinOp::BitOr => {
                        self.emit(format!("LDSP {l}"));
                        let ins = match op {
                            BinOp::Add => "ADDSP",
                            BinOp::Sub => "SUBSP",
                            BinOp::BitAnd => "ANDSP",
                            BinOp::BitXor => "XORSP",
                            _ => "ORSP",
                        };
                        self.emit(format!("{ins} {r}"));
                        Ok(common)
                    }
                    BinOp::Mul | BinOp::Div | BinOp::Mod => {
                        self.c.used_runtime = true;
                        self.emit(format!("LDSP {r}"));
                        self.emit("PUSH");
                        self.emit(format!("LDSP {}", l + 1));
                        self.emit("PUSH");
                        let base = match op {
                            BinOp::Mul => "mul",
                            BinOp::Div => "div",
                            _ => "mod",
                        };
                        let sign = if common == Type::UInt { "u32" } else { "i32" };
                        self.emit(format!("CALL __ex3_{base}_{sign}"));
                        self.emit("ADJSP 2");
                        Ok(common)
                    }
                    _ => {
                        self.emit(format!("LDSP {l}"));
                        self.emit(format!("CMPSP {r}"));
                        let br = match op {
                            BinOp::Eq => "BEQ",
                            BinOp::Ne => "BNE",
                            BinOp::Lt => {
                                if common == Type::UInt {
                                    "BULT"
                                } else {
                                    "BLT"
                                }
                            }
                            BinOp::Le => {
                                if common == Type::UInt {
                                    "BULE"
                                } else {
                                    "BLE"
                                }
                            }
                            BinOp::Gt => {
                                if common == Type::UInt {
                                    "BUGT"
                                } else {
                                    "BGT"
                                }
                            }
                            BinOp::Ge => {
                                if common == Type::UInt {
                                    "BUGE"
                                } else {
                                    "BGE"
                                }
                            }
                            _ => unreachable!(),
                        };
                        self.bool_branch(br);
                        Ok(Type::Int)
                    }
                }
            }
            ExprKind::Call(n, args) => {
                let sig = self.c.funcs.get(n).cloned().ok_or_else(|| {
                    CcError::new(e.span, format!("call to undeclared function `{n}`"))
                })?;
                if args.len() != sig.params.len() {
                    return Err(CcError::new(
                        e.span,
                        format!(
                            "function `{n}` expects {} arguments, got {}",
                            sig.params.len(),
                            args.len()
                        ),
                    ));
                }
                let mut pushed = 0;
                for (arg, _) in args.iter().zip(&sig.params).rev() {
                    scalar(self.expr(arg, d, shift + pushed)?, arg.span)?;
                    self.emit("PUSH");
                    pushed += 1
                }
                let target = match n.as_str() {
                    "putchar" => {
                        self.c.used_runtime = true;
                        "__ex3_putchar"
                    }
                    "getchar" => {
                        self.c.used_runtime = true;
                        "__ex3_getchar"
                    }
                    _ => n,
                };
                self.emit(format!("CALL {target}"));
                if pushed > 0 {
                    self.emit(format!("ADJSP {pushed}"))
                }
                Ok(sig.ret)
            }
        }
    }
    fn logical(
        &mut self,
        op: BinOp,
        a: &Expr,
        b: &Expr,
        d: usize,
        shift: usize,
    ) -> Result<Type, CcError> {
        let short = self.c.fresh("logic");
        let end = self.c.fresh("logicend");
        scalar(self.expr(a, d, shift)?, a.span)?;
        self.emit("CMP 0");
        if op == BinOp::And {
            self.emit(format!("BEQ {short}"))
        } else {
            self.emit(format!("BNE {short}"))
        }
        scalar(self.expr(b, d, shift)?, b.span)?;
        self.emit("CMP 0");
        if op == BinOp::And {
            self.emit(format!("BEQ {short}"));
            self.emit("LDA 1")
        } else {
            self.emit(format!("BNE {short}"));
            self.emit("LDA 0")
        }
        self.emit(format!("JMP {end}"));
        self.emit(format!("{short}:"));
        self.emit(if op == BinOp::And { "LDA 0" } else { "LDA 1" });
        self.emit(format!("{end}:"));
        Ok(Type::Int)
    }
    fn bool_branch(&mut self, br: &str) {
        let yes = self.c.fresh("true");
        let end = self.c.fresh("boolend");
        self.emit(format!("{br} {yes}"));
        self.emit("LDA 0");
        self.emit(format!("JMP {end}"));
        self.emit(format!("{yes}:"));
        self.emit("LDA 1");
        self.emit(format!("{end}:"));
    }
    fn load_const(&mut self, v: u32) {
        let signed = v as i32;
        if (-32768..=32767).contains(&signed) {
            self.emit(format!("LDA {signed}"))
        } else {
            self.emit("CLA");
            self.emit(format!("LDHI 0x{:04x}", v >> 16));
            self.emit(format!("LDLO 0x{:04x}", v & 0xffff));
        }
    }
}

fn scalar(t: Type, s: Span) -> Result<(), CcError> {
    if t == Type::Void {
        Err(CcError::new(
            s,
            "void expression used where a value is required",
        ))
    } else {
        Ok(())
    }
}
fn count_locals(s: &Stmt) -> usize {
    match &s.kind {
        StmtKind::Decl(..) => 1,
        StmtKind::Block(x) => x.iter().map(count_locals).sum(),
        StmtKind::If(_, a, b) => count_locals(a) + b.as_deref().map(count_locals).unwrap_or(0),
        StmtKind::While(_, b) | StmtKind::Label(_, b) => count_locals(b),
        StmtKind::Switch(_, p) => p
            .iter()
            .map(|x| {
                if let SwitchPart::Stmt(s) = x {
                    count_locals(s)
                } else {
                    0
                }
            })
            .sum(),
        _ => 0,
    }
}
fn max_temps_expr(e: &Expr) -> usize {
    match &e.kind {
        ExprKind::Unary(_, x) | ExprKind::Assign(_, x) => max_temps_expr(x),
        ExprKind::Binary(BinOp::And | BinOp::Or, a, b) => max_temps_expr(a).max(max_temps_expr(b)),
        ExprKind::Binary(_, a, b) => max_temps_expr(a).max(1 + max_temps_expr(b)).max(2),
        ExprKind::Call(_, a) => a.iter().map(max_temps_expr).max().unwrap_or(0),
        _ => 0,
    }
}
fn max_temps_stmt(s: &Stmt) -> usize {
    match &s.kind {
        StmtKind::Expr(e) | StmtKind::Return(Some(e)) => max_temps_expr(e),
        StmtKind::Decl(_, _, Some(e)) => max_temps_expr(e),
        StmtKind::Block(x) => x.iter().map(max_temps_stmt).max().unwrap_or(0),
        StmtKind::If(e, a, b) => max_temps_expr(e)
            .max(max_temps_stmt(a))
            .max(b.as_deref().map(max_temps_stmt).unwrap_or(0)),
        StmtKind::While(e, b) => max_temps_expr(e).max(max_temps_stmt(b)),
        StmtKind::Switch(e, p) => 1.max(max_temps_expr(e)).max(
            p.iter()
                .map(|x| {
                    if let SwitchPart::Stmt(s) = x {
                        max_temps_stmt(s)
                    } else {
                        0
                    }
                })
                .max()
                .unwrap_or(0),
        ),
        StmtKind::Label(_, b) => max_temps_stmt(b),
        _ => 0,
    }
}
fn definitely_returns(s: &Stmt) -> bool {
    match &s.kind {
        StmtKind::Return(_) => true,
        StmtKind::Block(xs) => xs.iter().any(definitely_returns),
        StmtKind::If(_, a, b) => {
            definitely_returns(a) || b.as_deref().is_some_and(definitely_returns)
        }
        StmtKind::While(_, b) | StmtKind::Label(_, b) => definitely_returns(b),
        StmtKind::Switch(_, p) => p
            .iter()
            .any(|x| matches!(x,SwitchPart::Stmt(s) if definitely_returns(s))),
        _ => false,
    }
}
fn reserved(s: &str) -> bool {
    s == "putchar" || s == "getchar" || s.starts_with("__cc_") || s.starts_with("__ex3_")
}
fn collect_labels(s: &Stmt, f: &str) -> Result<HashMap<String, String>, CcError> {
    fn walk(s: &Stmt, m: &mut HashMap<String, String>, f: &str) -> Result<(), CcError> {
        match &s.kind {
            StmtKind::Label(n, b) => {
                if m.insert(n.clone(), format!("__cc_user_{f}_{n}")).is_some() {
                    return Err(CcError::new(s.span, format!("duplicate label `{n}`")));
                }
                walk(b, m, f)?
            }
            StmtKind::Block(x) => {
                for s in x {
                    walk(s, m, f)?
                }
            }
            StmtKind::If(_, a, b) => {
                walk(a, m, f)?;
                if let Some(b) = b {
                    walk(b, m, f)?
                }
            }
            StmtKind::While(_, b) => walk(b, m, f)?,
            StmtKind::Switch(_, p) => {
                for x in p {
                    if let SwitchPart::Stmt(s) = x {
                        walk(s, m, f)?
                    }
                }
            }
            _ => {}
        }
        Ok(())
    }
    let mut m = HashMap::new();
    walk(s, &mut m, f)?;
    Ok(m)
}
fn const_expr(e: &Expr) -> Result<(u32, Type), String> {
    match &e.kind {
        ExprKind::Number(v, u) => Ok((*v, if *u { Type::UInt } else { Type::Int })),
        ExprKind::Unary(op, x) => {
            let (v, t) = const_expr(x)?;
            Ok((
                match op {
                    UnOp::BitNot => !v,
                    UnOp::Not => (v == 0) as u32,
                    UnOp::Plus => v,
                    UnOp::Neg => 0u32.wrapping_sub(v),
                },
                if *op == UnOp::Not { Type::Int } else { t },
            ))
        }
        ExprKind::Binary(op, a, b) => {
            let (x, ta) = const_expr(a)?;
            let (y, tb) = const_expr(b)?;
            let u = ta == Type::UInt || tb == Type::UInt;
            let v = match op {
                BinOp::Add => x.wrapping_add(y),
                BinOp::Sub => x.wrapping_sub(y),
                BinOp::Mul => x.wrapping_mul(y),
                BinOp::Div => {
                    if y == 0 {
                        return Err("division by zero in constant expression".into());
                    } else if u {
                        x / y
                    } else {
                        (x as i32).wrapping_div(y as i32) as u32
                    }
                }
                BinOp::Mod => {
                    if y == 0 {
                        return Err("division by zero in constant expression".into());
                    } else if u {
                        x % y
                    } else {
                        (x as i32).wrapping_rem(y as i32) as u32
                    }
                }
                BinOp::BitAnd => x & y,
                BinOp::BitXor => x ^ y,
                BinOp::BitOr => x | y,
                BinOp::Lt => {
                    if u {
                        (x < y) as u32
                    } else {
                        ((x as i32) < y as i32) as u32
                    }
                }
                BinOp::Le => {
                    if u {
                        (x <= y) as u32
                    } else {
                        ((x as i32) <= y as i32) as u32
                    }
                }
                BinOp::Gt => {
                    if u {
                        (x > y) as u32
                    } else {
                        ((x as i32) > y as i32) as u32
                    }
                }
                BinOp::Ge => {
                    if u {
                        (x >= y) as u32
                    } else {
                        ((x as i32) >= y as i32) as u32
                    }
                }
                BinOp::Eq => (x == y) as u32,
                BinOp::Ne => (x != y) as u32,
                BinOp::And => ((x != 0) && (y != 0)) as u32,
                BinOp::Or => ((x != 0) || (y != 0)) as u32,
            };
            let cmp = matches!(
                op,
                BinOp::Lt
                    | BinOp::Le
                    | BinOp::Gt
                    | BinOp::Ge
                    | BinOp::Eq
                    | BinOp::Ne
                    | BinOp::And
                    | BinOp::Or
            );
            Ok((
                v,
                if cmp {
                    Type::Int
                } else if u {
                    Type::UInt
                } else {
                    Type::Int
                },
            ))
        }
        _ => Err("initializer/case is not an integer constant expression".into()),
    }
}

const RUNTIME: &str = r#"
__ex3_putchar:
SIO
__ex3_putchar_wait:
SKO
JMP __ex3_putchar_wait
LDSP 1
OUT
RET
__ex3_getchar:
SIO
__ex3_getchar_wait:
SKI
JMP __ex3_getchar_wait
CLA
INP
RET
__ex3_mul_u32:
ADJSP -4
CLA
STSP 0
LDSP 6
STSP 1
__ex3_mulu_loop:
LDSP 1
CMP 0
BEQ __ex3_mulu_end
LDA 1
STSP 2
LDSP 5
STSP 3
__ex3_mulu_inner:
LDSP 2
ADDSP 2
BUGE __ex3_mulu_take
CMPSP 1
BUGT __ex3_mulu_take
STSP 2
LDSP 3
ADDSP 3
STSP 3
JMP __ex3_mulu_inner
__ex3_mulu_take:
LDSP 1
SUBSP 2
STSP 1
LDSP 0
ADDSP 3
STSP 0
JMP __ex3_mulu_loop
__ex3_mulu_end:
LDSP 0
ADJSP 4
RET
__ex3_div_u32:
ADJSP -4
CLA
STSP 1
LDSP 5
STSP 0
__ex3_divu_loop:
LDSP 0
CMPSP 6
BULT __ex3_divu_end
LDSP 6
STSP 2
LDA 1
STSP 3
__ex3_divu_inner:
LDSP 2
ADDSP 2
BUGE __ex3_divu_take
CMPSP 0
BUGT __ex3_divu_take
STSP 2
LDSP 3
ADDSP 3
STSP 3
JMP __ex3_divu_inner
__ex3_divu_take:
LDSP 0
SUBSP 2
STSP 0
LDSP 0
LDSP 1
ADDSP 3
STSP 1
JMP __ex3_divu_loop
__ex3_divu_end:
LDSP 1
ADJSP 4
RET
__ex3_mod_u32:
ADJSP -2
LDSP 3
STSP 0
__ex3_modu_loop:
LDSP 0
CMPSP 4
BULT __ex3_modu_end
LDSP 4
STSP 1
__ex3_modu_inner:
LDSP 1
ADDSP 1
BUGE __ex3_modu_take
CMPSP 0
BUGT __ex3_modu_take
STSP 1
JMP __ex3_modu_inner
__ex3_modu_take:
LDSP 0
SUBSP 1
STSP 0
JMP __ex3_modu_loop
__ex3_modu_end:
LDSP 0
ADJSP 2
RET
__ex3_mul_i32:
ADJSP -3
LDSP 4
CMP 0
BGE __ex3_muli_aok
STSP 0
CLA
SUBSP 0
__ex3_muli_aok:
STSP 0
LDSP 5
CMP 0
BGE __ex3_muli_bok
STSP 1
CLA
SUBSP 1
__ex3_muli_bok:
STSP 1
LDSP 1
PUSH
LDSP 1
PUSH
CALL __ex3_mul_u32
ADJSP 2
STSP 2
LDSP 4
CMP 0
BLT __ex3_muli_aneg
LDSP 5
CMP 0
BLT __ex3_muli_neg
JMP __ex3_muli_ret
__ex3_muli_aneg:
LDSP 5
CMP 0
BLT __ex3_muli_ret
__ex3_muli_neg:
CLA
SUBSP 2
STSP 2
__ex3_muli_ret:
LDSP 2
ADJSP 3
RET
__ex3_div_i32:
ADJSP -3
LDSP 4
CMP 0
BGE __ex3_divi_aok
STSP 0
CLA
SUBSP 0
__ex3_divi_aok:
STSP 0
LDSP 5
CMP 0
BGE __ex3_divi_bok
STSP 1
CLA
SUBSP 1
__ex3_divi_bok:
STSP 1
LDSP 1
PUSH
LDSP 1
PUSH
CALL __ex3_div_u32
ADJSP 2
STSP 2
LDSP 4
CMP 0
BLT __ex3_divi_aneg
LDSP 5
CMP 0
BLT __ex3_divi_neg
JMP __ex3_divi_ret
__ex3_divi_aneg:
LDSP 5
CMP 0
BLT __ex3_divi_ret
__ex3_divi_neg:
CLA
SUBSP 2
STSP 2
__ex3_divi_ret:
LDSP 2
ADJSP 3
RET
__ex3_mod_i32:
ADJSP -2
LDSP 3
CMP 0
BGE __ex3_modi_aok
STSP 0
CLA
SUBSP 0
__ex3_modi_aok:
STSP 0
LDSP 4
CMP 0
BGE __ex3_modi_bok
STSP 1
CLA
SUBSP 1
__ex3_modi_bok:
STSP 1
LDSP 1
PUSH
LDSP 1
PUSH
CALL __ex3_mod_u32
ADJSP 2
STSP 0
LDSP 3
CMP 0
BGE __ex3_modi_ret
CLA
SUBSP 0
STSP 0
__ex3_modi_ret:
LDSP 0
ADJSP 2
RET
"#;
