use crate::cc::sema::{StackOffset, UserLabel};

#[derive(Clone, Copy, Default)]
pub(super) struct LabelId(usize);

#[derive(Clone, Copy)]
pub(super) enum LabelKind {
    Return,
    Else,
    IfEnd,
    While,
    WhileEnd,
    SwitchEnd,
    Case,
    Default,
    Not,
    NotEnd,
    Logic,
    LogicEnd,
    True,
    BoolEnd,
}

impl LabelKind {
    fn prefix(self) -> &'static str {
        match self {
            Self::Return => "return",
            Self::Else => "else",
            Self::IfEnd => "ifend",
            Self::While => "while",
            Self::WhileEnd => "wend",
            Self::SwitchEnd => "swend",
            Self::Case => "case",
            Self::Default => "default",
            Self::Not => "not",
            Self::NotEnd => "notend",
            Self::Logic => "logic",
            Self::LogicEnd => "logicend",
            Self::True => "true",
            Self::BoolEnd => "boolend",
        }
    }
}

#[derive(Clone, Copy)]
pub(super) struct Label {
    id: LabelId,
    kind: LabelKind,
}

impl Label {
    fn render(self) -> String {
        format!("__cc_{}_{}", self.kind.prefix(), self.id.0)
    }
}

#[derive(Default)]
pub(super) struct LabelFactory {
    next: LabelId,
}

impl LabelFactory {
    pub(super) fn fresh(&mut self, kind: LabelKind) -> Label {
        let label = Label {
            id: self.next,
            kind,
        };
        self.next = LabelId(self.next.0 + 1);
        label
    }
}

#[derive(Clone, Copy)]
pub(super) enum BranchCondition {
    Equal,
    NotEqual,
    SignedLess,
    SignedLessEqual,
    SignedGreater,
    SignedGreaterEqual,
    UnsignedLess,
    UnsignedLessEqual,
    UnsignedGreater,
    UnsignedGreaterEqual,
}

impl BranchCondition {
    fn mnemonic(self) -> &'static str {
        match self {
            Self::Equal => "BEQ",
            Self::NotEqual => "BNE",
            Self::SignedLess => "BLT",
            Self::SignedLessEqual => "BLE",
            Self::SignedGreater => "BGT",
            Self::SignedGreaterEqual => "BGE",
            Self::UnsignedLess => "BULT",
            Self::UnsignedLessEqual => "BULE",
            Self::UnsignedGreater => "BUGT",
            Self::UnsignedGreaterEqual => "BUGE",
        }
    }
}

#[derive(Clone, Copy)]
pub(super) enum StackBinaryOp {
    Add,
    Subtract,
    And,
    Xor,
    Or,
}

impl StackBinaryOp {
    fn mnemonic(self) -> &'static str {
        match self {
            Self::Add => "ADDSP",
            Self::Subtract => "SUBSP",
            Self::And => "ANDSP",
            Self::Xor => "XORSP",
            Self::Or => "ORSP",
        }
    }
}

#[derive(Default)]
pub(super) struct Emitter {
    assembly: String,
}

impl Emitter {
    fn line(&mut self, line: impl AsRef<str>) {
        self.assembly.push_str(line.as_ref());
        self.assembly.push('\n');
    }
    pub(super) fn symbol_label(&mut self, symbol: &str) {
        self.line(format!("{symbol}:"));
    }
    pub(super) fn generated_header(&mut self) {
        self.line("; generated by ex3 cc");
        self.line("ORG 0x0010");
        self.call("main");
        self.line("HLT");
    }
    pub(super) fn append_assembly(&mut self, assembly: &str) {
        self.assembly.push_str(assembly);
    }
    pub(super) fn global(&mut self, symbol: &str, value: u32) {
        self.line(format!("{symbol}: HEX {value:08x}"));
    }
    pub(super) fn end(&mut self) {
        self.line("END");
    }
    pub(super) fn label(&mut self, label: Label) {
        self.line(format!("{}:", label.render()));
    }
    pub(super) fn user_label(&mut self, label: &UserLabel) {
        self.line(format!("{}:", label.0));
    }
    pub(super) fn load_sp(&mut self, offset: StackOffset) {
        self.line(format!("LDSP {offset}"));
    }
    pub(super) fn store_sp(&mut self, offset: StackOffset) {
        self.line(format!("STSP {offset}"));
    }
    pub(super) fn compare_sp(&mut self, offset: StackOffset) {
        self.line(format!("CMPSP {offset}"));
    }
    pub(super) fn stack_binary(&mut self, op: StackBinaryOp, offset: StackOffset) {
        self.line(format!("{} {offset}", op.mnemonic()));
    }
    pub(super) fn load_global(&mut self, symbol: &str) {
        self.line(format!("LDA {symbol}"));
    }
    pub(super) fn store_global(&mut self, symbol: &str) {
        self.line(format!("STA {symbol}"));
    }
    pub(super) fn load_immediate(&mut self, value: i32) {
        self.line(format!("LDA {value}"));
    }
    pub(super) fn load_high(&mut self, value: u16) {
        self.line(format!("LDHI 0x{value:04x}"));
    }
    pub(super) fn load_low(&mut self, value: u16) {
        self.line(format!("LDLO 0x{value:04x}"));
    }
    pub(super) fn adjust_sp(&mut self, amount: isize) {
        self.line(format!("ADJSP {amount}"));
    }
    pub(super) fn branch(&mut self, condition: BranchCondition, label: Label) {
        self.line(format!("{} {}", condition.mnemonic(), label.render()));
    }
    pub(super) fn jump(&mut self, label: Label) {
        self.line(format!("JMP {}", label.render()));
    }
    pub(super) fn jump_user(&mut self, label: &UserLabel) {
        self.line(format!("JMP {}", label.0));
    }
    pub(super) fn call(&mut self, symbol: &str) {
        self.line(format!("CALL {symbol}"));
    }
    pub(super) fn clear(&mut self) {
        self.line("CLA");
    }
    pub(super) fn complement(&mut self) {
        self.line("CMA");
    }
    pub(super) fn compare_zero(&mut self) {
        self.line("CMP 0");
    }
    pub(super) fn push(&mut self) {
        self.line("PUSH");
    }
    pub(super) fn ret(&mut self) {
        self.line("RET");
    }
    pub(super) fn finish(self) -> String {
        self.assembly
    }
}
