use super::frame::StackOffset;
use crate::cc::{sema::UserLabel, AssemblyLineDebugInfo, EmitDebugContext, GeneratedAssembly};

#[derive(Clone, Copy, Default)]
pub(super) struct LabelId(usize);

#[derive(Clone, Copy)]
pub(super) enum LabelKind {
    Return,
    Else,
    IfEnd,
    While,
    WhileEnd,
    SwitchEnd,
    Case,
    Default,
    Not,
    NotEnd,
    Logic,
    LogicEnd,
    True,
    BoolEnd,
}

impl LabelKind {
    fn prefix(self) -> &'static str {
        match self {
            Self::Return => "return",
            Self::Else => "else",
            Self::IfEnd => "ifend",
            Self::While => "while",
            Self::WhileEnd => "wend",
            Self::SwitchEnd => "swend",
            Self::Case => "case",
            Self::Default => "default",
            Self::Not => "not",
            Self::NotEnd => "notend",
            Self::Logic => "logic",
            Self::LogicEnd => "logicend",
            Self::True => "true",
            Self::BoolEnd => "boolend",
        }
    }
}

#[derive(Clone, Copy)]
pub(super) struct Label {
    id: LabelId,
    kind: LabelKind,
}

impl Label {
    fn render(self) -> String {
        format!("__cc_{}_{}", self.kind.prefix(), self.id.0)
    }
}

#[derive(Default)]
pub(super) struct LabelFactory {
    next: LabelId,
}

impl LabelFactory {
    pub(super) fn fresh(&mut self, kind: LabelKind) -> Label {
        let label = Label {
            id: self.next,
            kind,
        };
        self.next = LabelId(self.next.0 + 1);
        label
    }
}

#[derive(Clone, Copy)]
pub(super) enum BranchCondition {
    Equal,
    NotEqual,
    SignedLess,
    SignedLessEqual,
    SignedGreater,
    SignedGreaterEqual,
    UnsignedLess,
    UnsignedLessEqual,
    UnsignedGreater,
    UnsignedGreaterEqual,
}

impl BranchCondition {
    fn mnemonic(self) -> &'static str {
        match self {
            Self::Equal => "BEQ",
            Self::NotEqual => "BNE",
            Self::SignedLess => "BLT",
            Self::SignedLessEqual => "BLE",
            Self::SignedGreater => "BGT",
            Self::SignedGreaterEqual => "BGE",
            Self::UnsignedLess => "BULT",
            Self::UnsignedLessEqual => "BULE",
            Self::UnsignedGreater => "BUGT",
            Self::UnsignedGreaterEqual => "BUGE",
        }
    }
}

#[derive(Clone, Copy)]
pub(super) enum StackBinaryOp {
    Add,
    Subtract,
    And,
    Xor,
    Or,
}

impl StackBinaryOp {
    fn mnemonic(self) -> &'static str {
        match self {
            Self::Add => "ADDSP",
            Self::Subtract => "SUBSP",
            Self::And => "ANDSP",
            Self::Xor => "XORSP",
            Self::Or => "ORSP",
        }
    }
}

#[derive(Default)]
pub(super) struct Emitter {
    assembly: String,
    line_count: u32,
    debug_lines: Vec<AssemblyLineDebugInfo>,
    debug_context: Option<EmitDebugContext>,
}

impl Emitter {
    fn line(&mut self, line: impl AsRef<str>) {
        self.assembly.push_str(line.as_ref());
        self.assembly.push('\n');
        self.line_count = self
            .line_count
            .checked_add(1)
            .expect("generated assembly exceeds u32 line count");
    }
    fn instruction(&mut self, line: impl AsRef<str>) {
        let assembly_line = self
            .line_count
            .checked_add(1)
            .expect("generated assembly exceeds u32 line count");
        if let Some(context) = &self.debug_context {
            self.debug_lines.push(AssemblyLineDebugInfo {
                assembly_line,
                function_id: context.function_id,
                frame_base_delta: context.frame_base_delta,
                fixed_frame_state: context.fixed_frame_state,
                active_temporaries: context.active_temporaries.clone(),
                dynamic_stack_slots: context.dynamic_stack_slots.clone(),
            });
        }
        self.line(line);
    }
    pub(super) fn set_debug_context(&mut self, context: EmitDebugContext) {
        self.debug_context = Some(context);
    }
    pub(super) fn symbol_label(&mut self, symbol: &str) {
        self.line(format!("{symbol}:"));
    }
    pub(super) fn generated_header(&mut self) {
        self.line("; generated by ex3 cc");
        self.line("ORG 0x0010");
        self.call("main");
        self.instruction("HLT");
    }
    pub(super) fn append_assembly(&mut self, assembly: &str) {
        self.assembly.push_str(assembly);
        let added_lines = assembly.lines().count();
        self.line_count = self
            .line_count
            .checked_add(u32::try_from(added_lines).expect("appended assembly is too large"))
            .expect("generated assembly exceeds u32 line count");
    }
    pub(super) fn append_generated(&mut self, generated: GeneratedAssembly) {
        let line_offset = self.line_count;
        self.append_assembly(&generated.text);
        self.debug_lines
            .extend(generated.debug_lines.into_iter().map(|mut line| {
                line.assembly_line = line
                    .assembly_line
                    .checked_add(line_offset)
                    .expect("generated assembly exceeds u32 line count");
                line
            }));
    }
    pub(super) fn global(&mut self, symbol: &str, value: u32) {
        self.line(format!("{symbol}: HEX {value:08x}"));
    }
    pub(super) fn end(&mut self) {
        self.line("END");
    }
    pub(super) fn label(&mut self, label: Label) {
        self.line(format!("{}:", label.render()));
    }
    pub(super) fn user_label(&mut self, function: &str, label: &UserLabel) {
        self.line(format!("__cc_user_{function}_{}:", label.0));
    }
    pub(super) fn load_sp(&mut self, offset: StackOffset) {
        self.instruction(format!("LDSP {offset}"));
    }
    pub(super) fn store_sp(&mut self, offset: StackOffset) {
        self.instruction(format!("STSP {offset}"));
    }
    pub(super) fn compare_sp(&mut self, offset: StackOffset) {
        self.instruction(format!("CMPSP {offset}"));
    }
    pub(super) fn stack_binary(&mut self, op: StackBinaryOp, offset: StackOffset) {
        self.instruction(format!("{} {offset}", op.mnemonic()));
    }
    pub(super) fn load_global(&mut self, symbol: &str) {
        self.instruction(format!("LDA {symbol}"));
    }
    pub(super) fn store_global(&mut self, symbol: &str) {
        self.instruction(format!("STA {symbol}"));
    }
    pub(super) fn load_immediate(&mut self, value: i32) {
        self.instruction(format!("LDA {value}"));
    }
    pub(super) fn load_high(&mut self, value: u16) {
        self.instruction(format!("LDHI 0x{value:04x}"));
    }
    pub(super) fn load_low(&mut self, value: u16) {
        self.instruction(format!("LDLO 0x{value:04x}"));
    }
    pub(super) fn adjust_sp(&mut self, amount: isize) {
        self.instruction(format!("ADJSP {amount}"));
    }
    pub(super) fn branch(&mut self, condition: BranchCondition, label: Label) {
        self.instruction(format!("{} {}", condition.mnemonic(), label.render()));
    }
    pub(super) fn jump(&mut self, label: Label) {
        self.instruction(format!("JMP {}", label.render()));
    }
    pub(super) fn jump_user(&mut self, function: &str, label: &UserLabel) {
        self.instruction(format!("JMP __cc_user_{function}_{}", label.0));
    }
    pub(super) fn call(&mut self, symbol: &str) {
        self.instruction(format!("CALL {symbol}"));
    }
    pub(super) fn clear(&mut self) {
        self.instruction("CLA");
    }
    pub(super) fn complement(&mut self) {
        self.instruction("CMA");
    }
    pub(super) fn compare_zero(&mut self) {
        self.instruction("CMP 0");
    }
    pub(super) fn push(&mut self) {
        self.instruction("PUSH");
    }
    pub(super) fn ret(&mut self) {
        self.instruction("RET");
    }
    pub(super) fn finish(self) -> GeneratedAssembly {
        GeneratedAssembly {
            text: self.assembly,
            debug_lines: self.debug_lines,
        }
    }
}
