; generated by ex3 cc
ORG 0x0010
CALL main
HLT
identity:
ADJSP 0
LDSP 1
JMP __cc_return_0
__cc_return_0:
ADJSP 0
RET
combine:
ADJSP -3
LDSP 4
STSP 1
LDSP 5
STSP 2
LDSP 1
ADDSP 2
STSP 1
LDSP 6
STSP 2
LDSP 1
ADDSP 2
STSP 0
LDSP 0
STSP 1
LDA 10
STSP 2
LDSP 1
CMPSP 2
BGT __cc_true_4
LDA 0
JMP __cc_boolend_5
__cc_true_4:
LDA 1
__cc_boolend_5:
CMP 0
BEQ __cc_else_2
LDSP 0
STSP 1
CLA
SUBSP 1
STSP 0
JMP __cc_ifend_3
__cc_else_2:
LDSP 0
STSP 1
LDA global_value
STSP 2
LDSP 1
ADDSP 2
STSP 0
__cc_ifend_3:
__cc_while_6:
LDSP 0
STSP 1
LDA 0
STSP 2
LDSP 1
CMPSP 2
BLT __cc_true_8
LDA 0
JMP __cc_boolend_9
__cc_true_8:
LDA 1
__cc_boolend_9:
CMP 0
BEQ __cc_wend_7
LDSP 0
STSP 1
LDA 1
STSP 2
LDSP 1
ADDSP 2
STSP 0
JMP __cc_while_6
__cc_wend_7:
LDSP 0
CMP 0
BEQ __cc_not_10
LDA 0
JMP __cc_notend_11
__cc_not_10:
LDA 1
__cc_notend_11:
JMP __cc_return_1
__cc_return_1:
ADJSP 3
RET
main:
ADJSP 0
LDA 3
PUSH
LDA 2
PUSH
LDA 1
PUSH
CALL identity
ADJSP 1
PUSH
CALL combine
ADJSP 3
JMP __cc_return_12
__cc_return_12:
ADJSP 0
RET
global_value: HEX 00000003
END
