; generated by ex3 cc
ORG 0x0010
CALL main
HLT
classify:
ADJSP -2
LDSP 3
STSP 0
LDA 3
STSP 1
LDSP 0
ANDSP 1
STSP 0
LDA 0
CMPSP 0
BEQ __cc_case_2
LDA 1
CMPSP 0
BEQ __cc_case_3
JMP __cc_default_4
__cc_case_2:
LDA 10
JMP __cc_return_0
__cc_case_3:
LDA 20
JMP __cc_return_0
__cc_default_4:
LDA 30
JMP __cc_return_0
__cc_swend_1:
__cc_return_0:
ADJSP 2
RET
main:
ADJSP -3
LDA 0
STSP 0
LDA 0
STA total
__cc_while_6:
LDSP 0
STSP 1
LDA 4
STSP 2
LDSP 1
CMPSP 2
BLT __cc_true_8
LDA 0
JMP __cc_boolend_9
__cc_true_8:
LDA 1
__cc_boolend_9:
CMP 0
BEQ __cc_wend_7
LDSP 0
STSP 1
LDA 1
STSP 2
LDSP 1
ADDSP 2
STSP 0
LDSP 0
STSP 1
LDA 2
STSP 2
LDSP 1
CMPSP 2
BEQ __cc_true_12
LDA 0
JMP __cc_boolend_13
__cc_true_12:
LDA 1
__cc_boolend_13:
CMP 0
BEQ __cc_else_10
JMP __cc_while_6
JMP __cc_ifend_11
__cc_else_10:
__cc_ifend_11:
LDA total
STSP 1
LDSP 0
STSP 2
LDSP 1
ADDSP 2
STA total
JMP __cc_while_6
__cc_wend_7:
LDA total
STSP 1
LDA 8
STSP 2
LDSP 1
CMPSP 2
BNE __cc_true_20
LDA 0
JMP __cc_boolend_21
__cc_true_20:
LDA 1
__cc_boolend_21:
CMP 0
BEQ __cc_logic_18
LDA total
STSP 1
LDA 9
STSP 2
LDSP 1
CMPSP 2
BNE __cc_true_22
LDA 0
JMP __cc_boolend_23
__cc_true_22:
LDA 1
__cc_boolend_23:
CMP 0
BEQ __cc_logic_18
LDA 1
JMP __cc_logicend_19
__cc_logic_18:
LDA 0
__cc_logicend_19:
CMP 0
BNE __cc_logic_16
LDA 2
PUSH
CALL classify
ADJSP 1
STSP 1
LDA 30
STSP 2
LDSP 1
CMPSP 2
BNE __cc_true_24
LDA 0
JMP __cc_boolend_25
__cc_true_24:
LDA 1
__cc_boolend_25:
CMP 0
BNE __cc_logic_16
LDA 0
JMP __cc_logicend_17
__cc_logic_16:
LDA 1
__cc_logicend_17:
CMP 0
BEQ __cc_else_14
JMP __cc_user_main_0
JMP __cc_ifend_15
__cc_else_14:
__cc_ifend_15:
LDA 42
JMP __cc_return_5
__cc_user_main_0:
LDA 1
JMP __cc_return_5
__cc_return_5:
ADJSP 3
RET
total: HEX 00000000
END
